export enum EGlobalActions {
  SearchOpen = "search-open",
  SearchClose = "search-close",
  CatalogOpen = "catalog-open",
  CatalogClose = "catalog-close",
  CatalogToggle = "catalog-toggle",
  CatalogLvl2Open = "catalog-lvl2-open",
  CatalogLvl2Close = "catalog-lvl2-close",
  FiltersOpen = "filters-open",
  FiltersClose = "filters-close",
  MobileBottomMenuOpen = "mobile-bottom-menu-open",
  MobileBottomMenuClose = "mobile-bottom-menu-close",
  MenuOpen = "menu-open",
  MenuClose = "menu-close",
  MenuToggle = "menu-toggle",
  ModalOpen = "modal-open",
  ModalClose = "modal-close",
  DrawerOpen = "drawer-open",
  DrawerClose = "drawer-close"
}